// Global Salesforce jargon list for the caveman lint (ARCHITECTURE.md, Caveman <-> Technical toggle). The lint set
// is this list union `concept.terms[].term` of the lesson's concepts; caveman text before the reveal step may
// contain none of them (case-insensitive, word boundary; lint.ts adds an optional plural suffix).
// A term may be marked case-sensitive when its lowercase form is an ordinary English word ("the rest of them").
export interface JargonTerm {
  term: string;
  caseSensitive?: boolean;
}

export const JARGON_TERMS: readonly JargonTerm[] = [
  // Language and query
  { term: 'Apex' },
  { term: 'Apex class' },
  { term: 'Apex REST' },
  { term: 'asynchronous Apex' },
  { term: 'SOQL' },
  { term: 'SOSL' },
  { term: 'SOQL injection' },
  { term: 'DML' },
  { term: 'trigger' },
  { term: 'savepoint' },
  { term: 'rollback' },
  { term: 'governor limit' },
  { term: 'heap' },
  { term: 'CPU time' },
  { term: 'callout' },
  { term: 'test class' },
  { term: 'code coverage' },
  { term: 'invocable' },
  { term: 'schedulable' },
  { term: 'Queueable' },
  { term: 'Batch Apex' },
  { term: 'batchable' },
  { term: 'future method' },
  // Data model
  { term: 'sObject' },
  { term: 'custom object' },
  { term: 'standard object' },
  { term: 'custom field' },
  { term: 'record type' },
  { term: 'page layout' },
  { term: 'lookup relationship' },
  { term: 'master-detail' },
  { term: 'validation rule' },
  { term: 'formula field' },
  { term: 'roll-up summary' },
  { term: 'external ID' },
  { term: 'Big Object' },
  { term: 'custom setting' },
  { term: 'custom metadata' },
  { term: 'metadata' },
  { term: 'Metadata API' },
  { term: 'Tooling API' },
  // Security and sharing
  { term: 'OWD' },
  { term: 'org-wide default' },
  { term: 'role hierarchy' },
  { term: 'sharing rule' },
  { term: 'sharing set' },
  { term: 'permission set' },
  { term: 'permission set group' },
  { term: 'profile' },
  { term: 'FLS' },
  { term: 'field-level security' },
  { term: 'public group' },
  { term: 'queue' },
  { term: 'territory' },
  { term: 'Shield' },
  { term: 'Event Monitoring' },
  // Environments and platform
  { term: 'Salesforce' },
  { term: 'org' },
  { term: 'sandbox' },
  { term: 'scratch org' },
  { term: 'tenant' },
  { term: 'multitenant' },
  { term: 'multi-tenant' },
  { term: 'multitenancy' },
  { term: 'Lightning' },
  { term: 'LWC' },
  { term: 'Aura' },
  { term: 'Visualforce' },
  { term: 'Experience Cloud' },
  { term: 'Sales Cloud' },
  { term: 'Service Cloud' },
  { term: 'AppExchange' },
  { term: 'managed package' },
  { term: 'unlocked package' },
  { term: 'Trailhead' },
  { term: 'Einstein' },
  { term: 'Platform Cache' },
  { term: 'API version' },
  { term: 'Data Loader' },
  // Automation
  { term: 'Flow' },
  { term: 'Flow Builder' },
  { term: 'Process Builder' },
  { term: 'workflow rule' },
  { term: 'platform event' },
  { term: 'CDC' },
  { term: 'Change Data Capture' },
  // Integration
  { term: 'Named Credential' },
  { term: 'Connected App' },
  { term: 'OAuth' },
  { term: 'REST', caseSensitive: true },
  { term: 'SOAP', caseSensitive: true },
  { term: 'Bulk API' },
  { term: 'Composite API' },
  { term: 'Streaming API' },
  { term: 'Enterprise WSDL' },
  { term: 'PK chunking' },
  // Scale and performance
  { term: 'skinny table' },
  { term: 'selectivity' },
  { term: 'selective' },
  { term: 'index' },
  { term: 'indices' },
  { term: 'LDV' },
  { term: 'large data volume' },
  { term: 'data skew' },
  { term: 'ownership skew' },
  { term: 'lookup skew' },
  { term: 'row lock' },
  { term: 'lock contention' },
];

export const JARGON_TERM_STRINGS: readonly string[] = JARGON_TERMS.map((entry) => entry.term);
